development:
  adapter: postgresql
  encoding: unicode
  database: knightrider_development
  pool: 2
  min_messages: warning

test: &test
  adapter: postgresql
  encoding: unicode
  database: knightrider_computing_test
  pool: 2
  min_messages: error

cucumber:
  <<: *test